# Generated by Django 4.2.20 on 2025-03-24 13:41

import apps.generations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_ru', models.TextField()),
                ('prompt_en', models.TextField()),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.generations.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='users.telegramuser')),
            ],
        ),
    ]
