# Generated by Django 4.2.20 on 2025-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generations/'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='prompt_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
