# Generated by Django 4.2.21 on 2025-05-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0002_alter_generation_id_alter_generation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='prompt_ru',
        ),
    ]
