# Generated by Django 4.2.21 on 2025-05-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0003_remove_generation_prompt_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='parameters',
        ),
    ]
