worker_processes 1;
events { worker_connections 1024; }

http {
    sendfile on;
    upstream backend {
        server backend:8000;
    }
    upstream bot {
        server bot:8000;  # Если бот будет отвечать по HTTP
    }
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /media/ {
            alias /app/backend/media/;
        }

        # Остальные настройки (например, для статики) можно добавить по необходимости
    }
}

#При ручной установке сертификата Lets Encrypt:

#worker_processes 1;
#events { worker_connections 1024; }

#http {
    #sendfile on;

    #upstream backend {
        #server backend:8000;
    #}
    #upstream bot {
        #server bot:8000;  # Если бот работает по HTTP
    #}

    # Редирект с HTTP на HTTPS
    #server {
        #listen 80;
        #server_name tattisketch.store;
        #eturn 301 https://$host$request_uri;
    #}

    #server {
        #listen 443 ssl;
        #server_name tattisketch.store;

        #ssl_certificate /etc/letsencrypt/live/tattisketch.store/fullchain.pem;
        #ssl_certificate_key /etc/letsencrypt/live/tattisketch.store/privkey.pem;
        #ssl_protocols TLSv1.2 TLSv1.3;
        #ssl_prefer_server_ciphers on;

        #location / {
            #proxy_pass http://backend;
            #proxy_set_header Host $host;
            #proxy_set_header X-Real-IP $remote_addr;
            #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #}

        #location /api/ {
            #proxy_pass http://backend;
            #proxy_set_header Host $host;
            #proxy_set_header X-Real-IP $remote_addr;
        #}

        #location /media/ {
            #alias /app/backend/media/;
        #}
    #}
#}
